apiVersion: v1
kind: Service
metadata:
  name: presidio-anonymizer-service
spec:
  selector:
    app: presidio-anonymizer
  ports:
  - protocol: TCP
    port: 5002
    targetPort: 3000
    nodePort: 31002
  type: NodePort
