apiVersion: v1
kind: Service
metadata:
  name: presidio-analyzer-service
spec:
  selector:
    app: presidio-analyzer
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 3000
      nodePort: 31001
  type: NodePort
